"""Verification that the OM training machinery is faithful to the paper.

Three checks, each of which would fail if any sign, factor, or indexing in the
Euler step (Eq. 3), the action (Eq. 5), or the force (Eq. 10) were wrong:

1. Self-consistency: the OM action of a computer theta* evaluated on its OWN
   deterministic (T=0) trajectory is ~0 (float32 integration error only).
2. Noise normalization: on a NOISY (finite-T) trajectory generated by theta*,
   the residuals recover exactly the injected unit Gaussians, so the mean
   action per (step, input) must equal N/2.
3. Trajectory recovery ("inverse problem"): training a fresh student (theta=0)
   on the deterministic trajectories of theta* must reach ~0 action and
   REPRODUCE those trajectories with its own autonomous dynamics.  The
   parameters themselves need not match: a handful of deterministic paths do
   not excite every coupling direction, so the quadratic action has a null
   space and many theta generate identical paths (LBFGS from 0 picks the
   minimum-norm one).
4. Identifiability with noise: training instead on NOISY trajectories of
   theta* (noise explores state space and breaks the coupling degeneracy)
   must recover a FUNCTIONALLY equivalent computer: its deterministic
   dynamics on fresh, unseen inputs z match those of theta*.  (Parameters
   converge too, but only at the statistical rate ~1/sqrt(data); directions
   that barely affect the dynamics -- e.g. the b vs W*zbar trade-off -- stay
   sloppy and are reported, not asserted.)

Usage:
    python test_om_recovery.py
"""

import torch

from thermo_student import ThermoStudent, N, DT

torch.manual_seed(1)
DEV = "cuda" if torch.cuda.is_available() else "cpu"

# Ground-truth computer with random parameters, and a batch of inputs.
truth = ThermoStudent(scale=0.5, seed=7).to(DEV)
z = torch.linspace(0.0, 1.0, 8, device=DEV)

# Deterministic (T=0) trajectories of the truth computer, recorded every step.
with torch.no_grad():
    traj = truth._rollout(z, M=1, beta=float("inf"), record_every=1)[:, :, 0, :]

# --- check 1: action of truth on its own noiseless trajectory ~ 0 ----------
loss_self = truth.om_loss(traj, z).item()
print(f"[1] OM action of theta* on its own T=0 trajectory: {loss_self:.3e} "
      f"(expect ~0)")
assert loss_self < 1e-6

# --- check 2: noisy trajectory -> action = N/2 ------------------------------
with torch.no_grad():
    ntraj = truth._rollout(z, M=1, seed=3, record_every=1)[:, :, 0, :]
loss_noisy = truth.om_loss(ntraj, z).item()
print(f"[2] OM action of theta* on its own NOISY trajectory: {loss_noisy:.4f} "
      f"(expect N/2 = {N / 2})")
assert abs(loss_noisy - N / 2) < 0.5

# --- check 3: recover theta* from the deterministic trajectories -----------
student = ThermoStudent().to(DEV)  # theta = 0
opt = torch.optim.LBFGS(student.parameters(), max_iter=60, history_size=40,
                        line_search_fn="strong_wolfe")

def closure():
    opt.zero_grad()
    loss = student.om_loss(traj, z)
    loss.backward()
    return loss

for r in range(10):
    loss = opt.step(closure)
print(f"[3] OM loss after recovery training: {loss.item():.3e} (expect ~0)")

# The student must REGENERATE the trajectories with its own dynamics ...
with torch.no_grad():
    straj = student._rollout(z, M=1, beta=float("inf"),
                             record_every=1)[:, :, 0, :]
traj_err = (straj - traj).abs().max().item()
print(f"    max |student rollout - traj| = {traj_err:.3e} (expect ~0)")
assert traj_err < 1e-2

# ... even though its parameters may sit elsewhere in the null space:
with torch.no_grad():
    db = (student.b - truth.b).abs().max().item()
    dW = (student.W - truth.W).abs().max().item()
    dJ = (student.coupling() - truth.coupling()).abs().max().item()
print(f"    param gaps (allowed): |db| {db:.2e}  |dW| {dW:.2e}  |dJ| {dJ:.2e}")

# --- check 4: noisy trajectories make theta* identifiable ------------------
M_noisy = 128
z = torch.linspace(0.0, 1.0, 16, device=DEV)
with torch.no_grad():
    ntraj4 = truth._rollout(z, M=M_noisy, seed=11,
                            record_every=1)          # (T, B, M, N)
T_, B_ = ntraj4.shape[0], ntraj4.shape[1]
ntraj_flat = ntraj4.permute(0, 1, 2, 3).reshape(T_, B_ * M_noisy, N)
z_flat = z.repeat_interleave(M_noisy)

student2 = ThermoStudent().to(DEV)
opt2 = torch.optim.LBFGS(student2.parameters(), max_iter=60, history_size=40,
                         line_search_fn="strong_wolfe")

def closure2():
    opt2.zero_grad()
    loss = student2.om_loss(ntraj_flat, z_flat)
    loss.backward()
    return loss

for r in range(8):
    loss2 = opt2.step(closure2)
print(f"[4] OM loss on noisy data: {loss2.item():.4f} (expect ~N/2 = {N / 2})")

with torch.no_grad():
    db2 = (student2.b - truth.b).abs().max().item()
    dW2 = (student2.W - truth.W).abs().max().item()
    dJ2 = (student2.coupling() - truth.coupling()).abs().max().item()
scale = truth.coupling().abs().max().item()
print(f"    param gaps (statistical): |db| {db2:.2e}  |dW| {dW2:.2e}  "
      f"|dJ| {dJ2:.2e}   (|J*| up to {scale:.2f})")

# Functional equivalence on UNSEEN inputs is the criterion that matters:
z_new = torch.tensor([0.123, 0.456, 0.789], device=DEV)
with torch.no_grad():
    r_truth = truth._rollout(z_new, M=1, beta=float("inf"),
                             record_every=1)[:, :, 0, :]
    r_stud = student2._rollout(z_new, M=1, beta=float("inf"),
                               record_every=1)[:, :, 0, :]
func_err = (r_truth - r_stud).abs().max().item()
print(f"    max |truth - student| over unseen-z trajectories: {func_err:.3e}")
# Statistical threshold for this data volume (errors shrink ~1/sqrt(data):
# verified 0.216 -> 0.082 when going 32 -> 128 samples x 8 -> 16 z-points).
assert func_err < 1.5e-1

print("all checks passed: OM machinery matches the paper end-to-end")
